In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("D:\\College_Work\\Project\\salary-prediction-notebook\\survey_results_public.csv")
df.head()

Respondent                                         MainBranch Hobbyist  \
0           1                     I am a developer by profession      Yes   
1           2                     I am a developer by profession       No   
2           3                        I code primarily as a hobby      Yes   
3           4                     I am a developer by profession      Yes   
4           5  I used to be a developer by profession, but no...      Yes   

    Age Age1stCode CompFreq  CompTotal  ConvertedComp             Country  \
0   NaN         13  Monthly        NaN            NaN             Germany   
1   NaN         19      NaN        NaN            NaN      United Kingdom   
2   NaN         15      NaN        NaN            NaN  Russian Federation   
3  25.0         18      NaN        NaN            NaN             Albania   
4  31.0         16      NaN        NaN            NaN       United States   

     CurrencyDesc  ...                  SurveyEase           SurveyLength  \
0   European Euro  ...  Neither easy nor difficult  Appropriate in length   
1  Pound sterling  ...                         NaN                    NaN   
2             NaN  ...  Neither easy nor difficult  Appropriate in length   
3    Albanian lek  ...                         NaN                    NaN   
4             NaN  ...                        Easy              Too short   

  Trans                                     UndergradMajor  \
0    No  Computer science, computer engineering, or sof...   
1   NaN  Computer science, computer engineering, or sof...   
2   NaN                                                NaN   
3    No  Computer science, computer engineering, or sof...   
4    No  Computer science, computer engineering, or sof...   

  WebframeDesireNextYear    WebframeWorkedWith  \
0           ASP.NET Core  ASP.NET;ASP.NET Core   
1                    NaN                   NaN   
2                    NaN                   NaN   
3                    NaN                   NaN   
4   Django;Ruby on Rails         Ruby on Rails   

                              WelcomeChange WorkWeekHrs YearsCode YearsCodePro  
0   Just as welcome now as I felt last year        50.0        36           27  
1  Somewhat more welcome now than last year         NaN         7            4  
2  Somewhat more welcome now than last year         NaN         4          NaN  
3  Somewhat less welcome now than last year        40.0         7            4  
4   Just as welcome now as I felt last year         NaN        15            8  

[5 rows x 61 columns]

In [3]:
#Country
#Educational level
#Employment
#Year of Exp
#Salary

In [4]:
df = df[['Country','EdLevel','Employment','YearsCodePro','ConvertedComp']]

In [5]:
df.shape

(64461, 5)

In [6]:
df  = df.rename({"ConvertedComp":"Salary"},axis = 1)
#One more way to rename

In [7]:
df.head()

Country                                          EdLevel  \
0             Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
1      United Kingdom     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2  Russian Federation                                              NaN   
3             Albania  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
4       United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

                                          Employment YearsCodePro  Salary  
0  Independent contractor, freelancer, or self-em...           27     NaN  
1                                 Employed full-time            4     NaN  
2                                                NaN          NaN     NaN  
3                                                NaN            4     NaN  
4                                 Employed full-time            8     NaN

In [8]:
df = df[df['Salary'].notnull()]
df.shape

(34756, 5)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34756 entries, 7 to 64154
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       34756 non-null  object 
 1   EdLevel       34188 non-null  object 
 2   Employment    34717 non-null  object 
 3   YearsCodePro  34621 non-null  object 
 4   Salary        34756 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.6+ MB


In [10]:
df.isnull().sum()

Country           0
EdLevel         568
Employment       39
YearsCodePro    135
Salary            0
dtype: int64

In [11]:
df = df.dropna()
df.isnull().sum()

Country         0
EdLevel         0
Employment      0
YearsCodePro    0
Salary          0
dtype: int64

In [12]:
df.sample(5)

Country                                          EdLevel  \
10189          Spain  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
9021         Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
35130    Netherlands     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
16517         Brazil               Professional degree (JD, MD, etc.)   
23818  United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

               Employment      YearsCodePro    Salary  
10189  Employed full-time                 7  298356.0  
9021   Employed full-time  Less than 1 year   51888.0  
35130  Employed full-time                 1  428064.0  
16517  Employed full-time                 2    8520.0  
23818  Employed full-time                11  110000.0

In [13]:
#I want full time employees
df  = df[df['Employment'] == 'Employed full-time']
df.shape


(30019, 5)

In [14]:
df.drop(columns = ['Employment'],inplace = True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30019 entries, 7 to 64154
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       30019 non-null  object 
 1   EdLevel       30019 non-null  object 
 2   YearsCodePro  30019 non-null  object 
 3   Salary        30019 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.1+ MB


In [16]:
df['Country'].value_counts()

Country
United States     7569
India             2425
United Kingdom    2287
Germany           1903
Canada            1178
                  ... 
Swaziland            1
Niger                1
Belize               1
Yemen                1
Andorra              1
Name: count, Length: 154, dtype: int64

In [17]:
#I will take  only the countries which has appeared more than 400 times

df = df[df.groupby(["Country"])['Country'].transform('count')> 400]

In [18]:
df['Country'].value_counts()

Country
United States         7569
India                 2425
United Kingdom        2287
Germany               1903
Canada                1178
Brazil                 991
France                 972
Spain                  670
Australia              659
Netherlands            654
Poland                 566
Italy                  560
Russian Federation     522
Sweden                 514
Name: count, dtype: int64

In [19]:
df.sample(5)

Country                                          EdLevel  \
5143        United States  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
18630              France       Other doctoral degree (Ph.D., Ed.D., etc.)   
20303       United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
56188       United States              Associate degree (A.A., A.S., etc.)   
23296  Russian Federation     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

      YearsCodePro     Salary  
5143             7   134000.0  
18630           11    54480.0  
20303            2   110000.0  
56188           15  1800000.0  
23296           15    37746.0

In [20]:
# I want ppl with salary < = 250000
# I want ppl with salary > = 10000
df = df[df['Salary'] >= 10000]
df = df[df['Salary'] <= 250000]

In [21]:
df.shape

(18491, 4)

In [22]:
df.sample(5)

Country                                            EdLevel  \
42779          Brazil  Some college/university study without earning ...   
50917  United Kingdom    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
15663         Germany    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
35076   United States       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
26934         Germany    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   

      YearsCodePro    Salary  
42779            4   18024.0  
50917            5  122796.0  
15663           17   38916.0  
35076           30  180000.0  
26934            8   45396.0

In [23]:
df['YearsCodePro'].unique()

array(['13', '4', '2', '7', '20', '1', '3', '10', '12', '29', '6', '28',
       '8', '23', '15', '25', '9', '11', 'Less than 1 year', '5', '21',
       '16', '18', '14', '32', '19', '22', '38', '30', '26', '27', '17',
       '24', '34', '35', '33', '36', '40', '39', 'More than 50 years',
       '31', '37', '41', '45', '42', '44', '43', '50', '49'], dtype=object)

In [24]:
#Filtering the data for exp

def filter_exp(x):
  if x ==  'More than 50 years':
    return 50
  if x == 'Less than 1 year':
    return 0.5
  return float(x)

In [25]:
filter_exp('More than 50 years')

50

In [26]:
df['YearsCodePro'] = df['YearsCodePro'].apply(filter_exp)

In [27]:
df['YearsCodePro'].unique()

array([13. ,  4. ,  2. ,  7. , 20. ,  1. ,  3. , 10. , 12. , 29. ,  6. ,
       28. ,  8. , 23. , 15. , 25. ,  9. , 11. ,  0.5,  5. , 21. , 16. ,
       18. , 14. , 32. , 19. , 22. , 38. , 30. , 26. , 27. , 17. , 24. ,
       34. , 35. , 33. , 36. , 40. , 39. , 50. , 31. , 37. , 41. , 45. ,
       42. , 44. , 43. , 49. ])

In [28]:
df.sample(5)

Country                                            EdLevel  \
19655  United States       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
47881         France    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
5630   United States       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
46758  United States  Some college/university study without earning ...   
50001          Italy  Some college/university study without earning ...   

       YearsCodePro    Salary  
19655           2.0  160000.0  
47881           1.0   37834.0  
5630           20.0  140000.0  
46758           5.0   65000.0  
50001           1.0   15564.0

In [29]:
df['EdLevel'].unique()

array(['Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Some college/university study without earning a degree',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Associate degree (A.A., A.S., etc.)',
       'Professional degree (JD, MD, etc.)',
       'Other doctoral degree (Ph.D., Ed.D., etc.)',
       'I never completed any formal education',
       'Primary/elementary school'], dtype=object)

In [30]:
def filter_education(x):
  if 'Bachelor’s degree' in x:
    return 'Bachelor’s degree'
  if 'Master’s degree' in x:
    return 'Master’s degree'
  if 'Professional degree' in x or 'Other doctoral' in x:
    return 'Post grad'
  return 'Less than a Bachelors'

In [31]:
filter_education('I never completed any formal education')

'Less than a Bachelors'

In [32]:
df['EdLevel'] = df['EdLevel'].apply(filter_education)

In [33]:
df.sample(5)

Country          EdLevel  YearsCodePro    Salary
19602  United States  Master’s degree          10.0   85000.0
14788  United States  Master’s degree           0.5   75000.0
3224   United States  Master’s degree           4.0  102000.0
25869        Germany  Master’s degree           5.0   86478.0
52617  United States  Master’s degree          14.0  125000.0

In [34]:
df['Country'].unique()


array(['United States', 'United Kingdom', 'Spain', 'Netherlands',
       'Germany', 'Canada', 'Italy', 'Brazil', 'France', 'India',
       'Sweden', 'Poland', 'Australia', 'Russian Federation'],
      dtype=object)

In [35]:
# Need to convert high level lang to machine level lang
# Country >> United States' >> 0 , 'United Kingdom'>> 1, 'Spain'>> 2, 'Netherlands >>3

In [36]:
from sklearn.preprocessing import LabelEncoder
le_country = LabelEncoder()


In [37]:
df['Country'] = le_country.fit_transform(df['Country'])
df['Country'].unique()

array([13, 12, 10,  7,  4,  2,  6,  1,  3,  5, 11,  8,  0,  9])

In [38]:
list(le_country.inverse_transform([9]))

['Russian Federation']

In [39]:
df.sample()

Country                EdLevel  YearsCodePro   Salary
17113       11  Less than a Bachelors          12.0  50928.0

In [40]:
le_education = LabelEncoder()
df['EdLevel'] = le_education.fit_transform(df['EdLevel'])
df['EdLevel'].unique()


array([0, 2, 1, 3])

In [41]:
list(le_education.inverse_transform([3]))

['Post grad']

In [42]:
df.head()

Country  EdLevel  YearsCodePro    Salary
7        13        0          13.0  116000.0
9        12        2           4.0   32315.0
10       12        0           2.0   40070.0
11       10        1           7.0   14268.0
12        7        1          20.0   38916.0

In [43]:
#Define I/P and O/P cols
X  = df[['Country','EdLevel','YearsCodePro']]
X

Country  EdLevel  YearsCodePro
7           13        0          13.0
9           12        2           4.0
10          12        0           2.0
11          10        1           7.0
12           7        1          20.0
...        ...      ...           ...
64113       13        1          15.0
64116       13        0           6.0
64122       13        1           4.0
64127       13        3          12.0
64129       13        2           4.0

[18491 rows x 3 columns]

In [44]:
y = df[['Salary']]
y

Salary
7      116000.0
9       32315.0
10      40070.0
11      14268.0
12      38916.0
...         ...
64113  225000.0
64116  150000.0
64122   70000.0
64127  140000.0
64129  150000.0

[18491 rows x 1 columns]

In [45]:
#ML >>>> Train >> Deploy
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()

In [46]:
linear_reg.fit(X,y)

LinearRegression()

In [47]:
y_pred = linear_reg.predict(X)

In [48]:
df.sample()

Country  EdLevel  YearsCodePro    Salary
47745       13        0          28.0  185000.0

In [49]:
print(mean_absolute_error(y,y_pred))
print(mean_squared_error(y,y_pred))
print(r2_score(y,y_pred))

30479.812570833874
1542506276.8748603
0.32368918978926575


In [50]:
linear_reg.predict([[2,1,1]])

d:\College_Work\Project\salary-prediction-notebook\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[29478.99934055]])

In [51]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=0)
dec_tree_reg.fit(X, y.values)

DecisionTreeRegressor(random_state=0)

In [52]:
y_pred = dec_tree_reg.predict(X)

In [53]:
print(mean_absolute_error(y,y_pred))
print(mean_squared_error(y,y_pred))
print(r2_score(y,y_pred))

19972.53583592743
865238589.711687
0.6206367387891172


In [54]:
from sklearn.ensemble import RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)
random_forest_reg.fit(X, y.values)

d:\College_Work\Project\salary-prediction-notebook\venv\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(random_state=0)

In [55]:
y_pred = random_forest_reg.predict(X)

In [56]:
print(mean_absolute_error(y,y_pred))
print(mean_squared_error(y,y_pred))
print(r2_score(y,y_pred))

20166.16047981287
869501373.5644207
0.6187677241572698


In [57]:
# Country , EdLEvel , YearCodeExp (Before applying the label encoder)
X = np.array([['United States','Post grad',15]])
X

array([['United States', 'Post grad', '15']], dtype='<U21')

In [58]:
X[:,0] = le_country.transform(X[:,0])
X[:,1] = le_education.transform(X[:,1])
X = X.astype(float)
X

array([[13.,  3., 15.]])

In [59]:
dec_tree_reg.predict(X)

d:\College_Work\Project\salary-prediction-notebook\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([159285.71428571])

In [60]:
#Deployment

In [61]:
#Save the data
import pickle

In [62]:
#Save model , label encoders for country and education
# pickle.dump(dec_tree_reg,open('dec_tree_reg.pkl','wb'))
# pickle.dump(le_country,open('le_country.pkl','wb'))
# pickle.dump(le_education,open('le_education.pkl','wb'))
data = {'model':dec_tree_reg,'le_country':le_country,'le_education':le_education}
with open('deployment.pkl','wb') as file:
  pickle.dump(data,file)

In [63]:
# with open('deployment.pkl','rb') as file:
#   data = pickle.load(file)

#   model = data['model']
#   le_country = data['le_country']
#   le_education = data['le_education']

# y_pred = dec_tree_reg.predict(X)
# y_pred

In [64]:
!pip install streamlit

  Using cached streamlit-1.49.1-py3-none-any.whl.metadata (9.5 kB)
  Using cached altair-5.5.0-py3-none-any.whl.metadata (11 kB)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
  Using cached cachetools-6.2.0-py3-none-any.whl.metadata (5.4 kB)
  Using cached click-8.2.1-py3-none-any.whl.metadata (2.5 kB)
  Using cached protobuf-6.32.1-cp310-abi3-win_amd64.whl.metadata (593 bytes)
  Using cached pyarrow-21.0.0-cp313-cp313-win_amd64.whl.metadata (3.4 kB)
  Using cached requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
  Using cached tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
  Using cached gitpython-3.1.45-py3-none-any.whl.metadata (13 kB)
  Using cached pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadat


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [65]:
%%writefile app.py
import streamlit as st
import pickle
import numpy as np



# def load_model():
#   with open('deployment.pkl','rb') as file:
#     data = pickle.load(file)
#   return data

pickle_in = open('deployment.pkl','rb')
data = pickle.load(pickle_in)
# data = load_model()

model = data['model']  #Algo
le_country = data['le_country']   #Label Encoder
le_education = data['le_education']


st.title("Salary Prediction")



countries = (
    'United States',
    'India',
    'United Kingdom',
    'Germany',
    'Canada',
    'Brazil',
    'France',
    'Spain',
    'Netherlands',
)

education = (
    'Less than a Bachelors',
    'Bachelor’s degree',
    'Master’s degree',
    'Post grad',
)

country = st.selectbox("Country",countries)
education = st.selectbox("Education Level",education)
experience = st.slider("Years of Experience",0,50)

ok = st.button("Calculate Salary")
if ok:
  X = np.array([[country,education,experience]])
  X[:,0] = le_country.transform(X[:,0])
  X[:,1] = le_education.transform(X[:,1])
  X = X.astype(float)
  salary = model.predict(X)
  st.subheader(f"The estimated salary is ${salary[0]:.2f}")


Writing app.py


In [66]:
!npm install localtunnel


added 22 packages in 3s

3 packages are looking for funding
  run `npm fund` for details


npm notice
npm notice New major version of npm available! 10.9.2 -> 11.6.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.6.0
npm notice To update run: npm install -g npm@11.6.0
npm notice


In [ ]:
!streamlit run app.py & npx localtunnel --port 8501